version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      tools:
        patterns:
          - bandit
          - black
          - flake8
          - flake8-simplify
          - isort
          - mypy
          - pre-commit
          - pylint
          - pydocstyle
        update-types:
          - minor
          - patch
      production:
        update-types:
          - minor
          - patch
