default_stages: [commit, push]
default_language_version:
  python: python3.12.4
repos:
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: ["."]
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
    - id: black
      args: [
        --line-length=120
      ]
      types: ['python']
  - repo: https://github.com/PyCQA/flake8
    rev: 7.0.0
    hooks:
    - id: flake8
      args: [
        "--max-line-length=120",
        "."
      ]
      types: ['python']
  -   repo: local
      hooks:
      -   id: pylint
          name: pylint
          entry: .venv/bin/python -m pylint
          language: system
          types: [python]
          args: ["-rn", "-sn"]
  - repo: https://github.com/pycqa/pydocstyle
    rev: 6.3.0
    hooks:
      - id: pydocstyle
        name: pydocstyle --convention==google
        args: [
          --convention=google
        ]
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.8
    hooks:
      - id: bandit
        args: [
          "-r",
          "."
        ]