[project]
name = "cwac"
version = "1.0.0"
description = "CWAC is a tool that can scan hundreds of websites for accessibility issues."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "beautifulsoup4==4.15.0",
    "lxml==6.1.1",
    "nltk==3.10.0",
    "numpy==2.5.1",
    "opencv-python==4.13.0.92",
    "opencv-python-headless==5.0.0.93",
    "pandas==3.0.5",
    "pandas-stubs==3.0.3.260530",
    "pyarrow==24.0.0",
    "pyfakefs==6.2.0",
    "requests==2.34.2",
    "responses==0.26.1",
    "selenium==4.46.0",
    "types-beautifulsoup4==4.12.0.20250516",
]

[dependency-groups]
dev = [
    "pytest>=9.1.1",
    "bandit==1.9.4",
    "flake8==7.3.0",
    "flake8-simplify==0.30.0",
    "mypy==2.3.0",
    "pre-commit==4.6.1",
    "pydocstyle==6.3.0",
    "pylint==4.0.6",
    "pytest==9.1.1",
    "pytest-mock==3.15.1",
    "ruff==0.16.0",
]
