indent-width = 2
line-length = 120

[format]
quote-style = 'single'

[lint]
ignore = [
  'E501', # don't check line length (mainly for comments)
  'D417'  # don't require documentation for every function parameter
]
select = [
  'E',    # pycodestyle
  'W',    # pycodestyle
  'F',    # Pyflakes
  'D',    # pydocstyle
  'SIM',  # flake8-simplify
  'I',    # isort
  'S',    # flake8-bandit
  'PLC'   # pylint conventions
]

[lint.pydocstyle]
convention = 'google'

[lint.per-file-ignores]
"tests/**/*.py" = [
  "S101" # allow using assert in tests
]
