indent-width = 2
line-length = 120

[format]
quote-style = 'single'

[lint]
ignore = [
  'E501', # don't check line length (mainly for comments)
  'D417'  # don't require documentation for every function parameter
]
select = [
  'E', # pycodestyle
  'W', # pycodestyle
  'F', # Pyflakes
  'D', # pydocstyle
  'I'  # isort
]

[lint.pydocstyle]
convention = 'google'
