indent-width = 2
line-length = 120

[format]
quote-style = 'single'

[lint]
ignore = [
  'D417' # don't require documentation for every function parameter
]
select = [
  'D', # pydocstyle
  'I'  # isort
]

[lint.pydocstyle]
convention = 'google'
