"""AuditManager - runs tests on a Browser."""

import logging
import os
import time
import urllib.parse
from typing import Any

import selenium
from selenium.webdriver.common.by import By

import src.filters
from config import Config
from src.analytics import Analytics
from src.browser import Browser
from src.output import CSVWriter

# pylint: disable=too-many-statements

logger = logging.getLogger('cwac')


class AuditManager:
  """Runs tests on browsers."""

  # Stores axe.min.js to prevent re-reading the file
  axe_core_js = ''

  def __init__(self, config: Config, browser: Browser, analytics: Analytics) -> None:
    """Init variables."""
    self.config = config
    self.browser = browser
    self.analytics = analytics
    self.audits: dict[Any, dict[Any, Any]] = {}
    self.filter = src.filters.URLFilter(self.config)

    # Stores URLs discarded as a key-value pair
    # of URL (str): reason (str). URLs are discarded
    # if they are blocked by anti-bot measures.
    self.discarded_urls: dict[str, str] = {}

  def register_audit(self, audit_name: str, audit_class: type[Any], **kwargs: Any) -> None:
    """Register audits to be run by run_audits().

    This can also be used to re-run a test with updated kwargs.

    Args:
        audit_name (str): Human-readable name for audit
        audit_class (Type[Any]): Reference to a class that runs the audit
        kwargs (Any): Arbitrary args to be passed to audit_class
    """
    # Register the audit (or update its kwargs)
    self.audits[audit_name] = {
      'audit_class': audit_class,
      'kwargs': kwargs,
    }

  def test_for_anti_bot(self) -> str:
    """Inspect the currently loaded page for anti-bot blocking.

    If bot blocking services such as Cloudflare, Incapsula, Azure Front Door,
    etc. are detected then:

    1. A screenshot is saved to the 'anti_bot_ss' folder.
    2. The result is written to an 'anti_bot.csv' file.
    3. The URL is added to the discarded_urls dict with the reason for discarding.

    Returns:
      str: 'Pass'|'Imperva'|'Cloudflare'|'Blocked'|'Azure Front Door'|'Red Shield'|'Cloudfront'
    """
    # Get the current URL
    try:
      url = self.browser.driver.current_url
    except selenium.common.exceptions.TimeoutException:
      logger.error('TimeoutException when getting current URL')
      return 'Pass'
    except selenium.common.exceptions.WebDriverException:
      logger.error('WebDriverException when getting current URL')
      return 'Pass'

    # If the URL is already discarded return its result
    if url in self.discarded_urls:
      return self.discarded_urls[url]

    # Get the page source
    try:
      page_source = self.browser.driver.page_source
    except selenium.common.exceptions.TimeoutException:
      logger.error('TimeoutException when getting page source')
      return 'Pass'
    except selenium.common.exceptions.WebDriverException:
      logger.error('WebDriverException when getting page source')
      return 'Pass'

    status = 'Pass'

    # Check for 'Incapsula' in the page source
    if 'Incapsula incident ID' in page_source:
      logger.error('Incapsula detected on %s', url)
      status = 'Imperva'

    # Check for 'red-shield.net' in the page source
    if 'please email support@red-shield.net' in page_source:
      logger.error('Red Shield detected on %s', url)
      status = 'Red Shield'

    # Check for 'Cloudflare' in the page source
    if 'Verifying you are human' in page_source and 'Ray ID' in page_source:
      logger.error('Cloudflare detected on %s', url)
      status = 'Cloudflare'

    # Check for 'CloudFront' in the page source
    if 'Generated by cloudfront (CloudFront)' in page_source:
      logger.error('CloudFront detected on %s', url)
      status = 'Cloudfront'

    # Check for 'Azure Front Door' in the page source
    afd_sig = """The request is blocked.</h2></div><div id="errorref">"""
    if afd_sig in page_source:
      logger.error('Azure Front Door detected on %s', url)
      status = 'Azure Front Door'

    if status != 'Pass':
      # Get the URL's organisation
      org = self.config.lookup_organisation(url)

      # Get URL's netloc
      netloc = urllib.parse.urlparse(url).netloc

      # Save screenshot
      # Make screenshot directory if it doesn't exist
      os.makedirs(
        f'./results/{self.config.audit_name}/anti_bot_ss',
        exist_ok=True,
      )
      self.browser.driver.save_screenshot(f'./results/{self.config.audit_name}/anti_bot_ss/{netloc}.png')

      # Write to anti-bot.csv
      csv_writer = CSVWriter()
      csv_writer.add_rows(
        [
          {
            'organisation': org['organisation'],
            'domain': netloc,
            'url': url,
            'anti_bot_check': status,
            'viewport_size': self.browser.viewport_size,
          }
        ]
      )
      csv_writer.write_csv_file(f'./results/{self.config.audit_name}/anti_bot.csv')
      self.discarded_urls[url] = status

    return status

  def check_for_details_elements(self) -> None:
    """Open <details> elements on current page if force_open_details_elements is True.

    Find all <details> elements on the page. If any are found, and if the config
    option force_open_details_elements is True, open them by setting their
    'open' attribute to an empty string. This ensures that the contents of the
    <details> elements are visible and can be audited.
    """
    details = self.browser.driver.find_elements(By.TAG_NAME, 'details')

    if len(details) == 0:
      return

    plural = ''
    if len(details) != 1:
      plural = 's'

    if not self.config.force_open_details_elements:
      logger.info('ignoring %i <details> element%s', len(details), plural)
      return

    logger.info('opening %i <details> element%s', len(details), plural)

    # Open all <details> elements
    for detail in details:
      if not detail.get_attribute('open'):
        try:
          self.browser.driver.execute_script("arguments[0].setAttribute('open', '')", detail)
        except Exception:  # pylint: disable=broad-exception-caught
          logger.warning("Could not open <details> element titled '%s'", detail.text)
          continue

  def run_audits(self) -> bool:  # noqa: PLR0915
    """Iterate through registered audits and runs them.

    Main entry point for running audits. Iterates through all registered audits
    and runs them on the current page at each configured viewport size.

    For each configured viewport size:

    1. The browser window is resized to the specified dimensions.
    2. For each audit configured to run at the current viewport size:
      1. The page is loaded
      2. The antibot check is run. If the page is blocked, the audit is skipped.
      3. Any details elements on the page are opened if force_open_details_elements is True.
      4. The audit is run and the results are written to a CSV file.
    3. The browser is refreshed. If the refresh fails, the browser is restarted.

    If an exception is raised during the execution of an audit, then the browser
    state is reset for the next audit:

    1. The browser is restarted.
    2. the viewport size is set again.
    3. The page is loaded again via `self.browser.get()`.

    Returns:
        bool: True if at least one audit successfully produced results, else False
    """
    logger.info('run_audits called')

    # Unique UUID string
    page_id = self.config.get_unique_id()

    # Tracks if at least one audit successfully produced results
    any_audit_succeeded = False

    # Re-run tests for each viewport size in config.json
    for index, viewport in enumerate(self.config.viewport_sizes):
      # Generate a unique audit ID
      audit_id = page_id + '_' + viewport

      self.browser.set_window_size(
        self.config.viewport_sizes[viewport]['width'],
        self.config.viewport_sizes[viewport]['height'],
      )

      for audit_name, audit in self.audits.items():
        # if viewport_to_test is set
        if (
          'viewport_to_test' in self.config.audit_plugins[audit_name]
          and self.config.audit_plugins[audit_name]['viewport_to_test'] != viewport
        ):
          # If the viewport is not the one we want to test, skip
          continue

        # Log the start of this audit
        logger.info(
          'Starting audit %s on %s',
          audit_name,
          audit['kwargs']['url'],
        )

        # The first time through this loop, we load the page to ensure that the
        # page is loaded with the correct viewport size. On subsequent
        # iterations, we load the page again to ensure that any changes (e.g.
        # injected JS) made by a previous audit do not affect the next audit.
        browser_status = self.browser.get(audit['kwargs']['url'])

        # Test for anti-bot measures
        if self.test_for_anti_bot() != 'Pass':
          # If URL is blocked, skip this URL
          logger.warning(
            'Skipping test %s on %s due to anti-bot',
            audit_name,
            audit['kwargs']['url'],
          )
          return any_audit_succeeded

        # If the browser fails to load the page, skip test
        if browser_status is False:
          logger.warning(
            'Skipping test %s on %s due to .get failure',
            audit_name,
            audit['kwargs']['url'],
          )
          continue

        self.check_for_details_elements()

        # Inject the audit ID
        audit['kwargs']['audit_id'] = audit_id

        # Inject the page ID
        audit['kwargs']['page_id'] = page_id

        # Inject the viewport size dict
        audit['kwargs']['viewport_size'] = self.config.viewport_sizes[viewport]

        start_time = time.perf_counter()

        # Run the tests
        test_instance = audit['audit_class'](config=self.config, browser=self.browser, **audit['kwargs'])

        try:
          audit_result = test_instance.run()
        except selenium.common.exceptions.WebDriverException:
          logger.exception(
            'Due to WebDriverException, test %s skipped on viewport %s for website %s',
            audit_name,
            viewport,
            audit['kwargs']['url'],
            exc_info=True,
          )
          # If the browser crashes, skip this test
          # and restart the browser
          self.browser.safe_restart()

          # Set window size
          self.browser.set_window_size(
            self.config.viewport_sizes[viewport]['width'],
            self.config.viewport_sizes[viewport]['height'],
          )

          continue

        except Exception:  # pylint: disable=broad-exception-caught
          logger.exception(
            'Unhandled exception %s %s',
            audit_name,
            audit['kwargs']['url'],
            exc_info=True,
          )
          continue

        logger.info('Test finished %s, %s', audit_name, audit['kwargs']['url'])

        # If audit_result is the boolean value True
        # a 'True' from the audit means to skip the audit
        # because it is not applicable to the current page,
        # but the audit did not fail to execute
        if audit_result is True:
          logger.info(
            'Skipping audit %s, %s',
            audit_name,
            audit['kwargs']['url'],
          )
          continue

        # If a test fails, .run() returns False
        if audit_result is False:
          logger.error(
            'Test failed %s, %s',
            audit_name,
            audit['kwargs']['url'],
          )
          continue

        # If a test returns an empty result, log an error
        if audit_result == []:
          logger.error(
            'Test gave empty response %s, %s',
            audit_name,
            audit['kwargs']['url'],
          )
          continue

        # Performance measurement
        end_time = time.perf_counter()
        elapsed_time = end_time - start_time
        logger.info(
          'Test time %s %s %.5f',
          audit_name,
          audit['kwargs']['url'],
          elapsed_time,
        )

        # Write results
        csv_writer = CSVWriter()
        csv_writer.add_rows(audit_result)
        csv_writer.write_csv_file(f'./results/{self.config.audit_name}/{audit_name}.csv')

        # At least one audit successfully produced results
        any_audit_succeeded = True

      # If we're not on the last viewport size
      if index < len(self.config.viewport_sizes) - 1:
        # Refresh the page
        try:
          self.browser.driver.refresh()
          # Give browser time to adjust to viewport size
          time.sleep(self.config.delay_between_viewports)
        except Exception:  # pylint: disable=broad-exception-caught
          logger.exception('Failed to refresh page')
          self.browser.safe_restart()
          break

    return any_audit_succeeded
